INFERANALYZE= /usr/local/Cellar/infer/0.10.0/lib/infer/infer/bin/InferAnalyze --results-dir '/Users/susion/Documents/Code/myproject/Boring/infer-out'  

CLUSTERS=cl1 cl2 cl3 cl4 cl5 cl6 cl7 cl8 cl9 cl10 cl11 cl12 cl13 cl14 cl15 cl16 cl17 cl18 cl19 cl20 cl21 cl22 cl23 cl24 cl25 cl26 cl27 cl28 cl29 cl30 cl31 cl32 cl33 cl34 cl35 cl36 cl37 cl38 cl39 cl40 cl41 cl42 cl43 cl44 cl45 cl46 cl47 cl48 cl49 cl50 cl51 cl52 cl53 cl54 cl55 cl56 cl57 cl58 cl59 cl60 cl61 cl62 cl63 cl64 cl65 cl66 cl67 cl68 cl69 cl70 cl71 cl72 cl73 cl74 cl75 cl76 cl77 cl78 cl79 cl80 cl81 cl82 cl83 cl84 cl85 cl86 cl87 cl88 cl89 cl90 cl91 cl92 cl93 cl94 cl95 cl96 cl97 cl98 cl99 cl100 cl101 cl102 cl103 cl104 cl105 cl106 cl107 cl108 cl109 cl110 cl111 cl112 cl113 cl114 cl115 cl116 cl117 cl118 cl119 cl120 cl121 cl122 cl123 cl124 cl125 cl126 cl127 cl128 

default: test

all: test

test: $(CLUSTERS)
	@echo

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/Album.java.1ffea4d6dba54f8b6572bdd83dca68d0
cl1: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl1.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/AlbumUtils.java.0feebb618538665f0dacb86a7a231df8
cl2: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl2.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/APIHelper.java.84477bffc286618ee69206c50679437f
cl3: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl3.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/BaseActivity.java.c0b092b46e48c92fdb9696443fe2c425
cl4: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl4.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/BaseFragment.java.f0d6c0971326110d289d341c890726f8
cl5: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl5.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/BasePresenter.java.b3455f765a6e2ccfd0816ba31139f374
cl6: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl6.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/BaseRVAdapter.java.bebeb3473680a8a2863ae825727b00b8
cl7: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl7.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/BaseURL.java.b57c19a7976dfde6f71df61a6e52515f
cl8: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl8.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/BeanTranslateUtils.java.a893319ffd2448c8bbbff1e2bebc8f9c
cl9: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl9.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/BroadcastUtils.java.517a5554dbdef9e1d8b743e0da7c795f
cl10: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl10.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/BuildConfig.java.5ee2813b87ced97e02fab4765874bdeb
cl11: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl11.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/BuildConfig.java.e51a98b7bca827a70188053b7767c042
cl12: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl12.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/ClientReceiverPresenter.java.eca6e992afc30a47a05c5bc51f172b1b
cl13: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl13.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/DataBaseOperateContract.java.fa624fa803315c17af3c60d5ca34b356
cl14: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl14.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/DbBaseOperate.java.4311be5f98aee0dcb17defb159dd201b
cl15: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl15.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/DbManager.java.0f0bc3f9e1b32758f0ac452839a5f92d
cl16: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl16.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/DividerMark.java.1f6b5f3851d52f6f8c801dc419922ab0
cl17: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl17.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/DownTask.java.20156826348ff0d76e0b0b88da2219a9
cl18: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl18.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/DrawerData.java.a5922dce63994fd13a593b5e9467f4f4
cl19: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl19.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/DrawerHeaderItemHandler.java.6c96b799971ed15512c7c3e64ee1cde6
cl20: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl20.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/DrawerItemHandler.java.64f2fddfb2cfd1f431de2e7af2d7370f
cl21: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl21.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/FastBlurUtil.java.41bf34995033653874c8679e24d434e7
cl22: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl22.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/FileDownContract.java.fca1d91022393e5e3de25ec7867197ac
cl23: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl23.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/FileDownloadPresenter.java.20f6c836877f1f1d05ee81b2aa43dcd5
cl24: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl24.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/FileUtils.java.5b9085d8c0387defe6e23c434d37e740
cl25: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl25.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/FragmentFactory.java.63f5f038bd57d4d9e675898aaeafa908
cl26: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl26.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/GetPlayListResult.java.b3fb6f5d1bb064df2140bf3138a3c10a
cl27: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl27.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/HttpUtils.java.e70c959cde1b0761dad3a53d00563cd2
cl28: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl28.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/ImageService.java.cc0ba3958b1b4e9bdc25bc5951532a79
cl29: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl29.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/ImageUtils.java.ca36453f6ca20b3298043d6ac9352d37
cl30: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl30.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/IMainUIPresenter.java.6f2f0be6332d44c94bc70492e6cf3d30
cl31: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl31.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/InterestingPageFragment.java.8be30d74803d60c0f478b4816e15e201
cl32: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl32.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/ItemHandler.java.50267d66b38fbc6e10ad0d583a48d202
cl33: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl33.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/ItemHandlerFactory.java.aa50ab68f9e294f04c1b46b44cee8444
cl34: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl34.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/IView.java.c818c03eed4f57117a21a40ebc53620b
cl35: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl35.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/LoadMoreRecycleView.java.ed493436e5e9985c91490a92d421b4f6
cl36: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl36.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/LoadMoreView.java.789f1f73d34ab2f9fd0990d93042970a
cl37: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl37.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/LocalMusicActivity.java.23c87ccf65ce5b2972ae289b3ef8f2d6
cl38: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl38.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/LocalMusicContract.java.7550d95bf9c79424f7f1b16c69b6d909
cl39: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl39.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/LocalMusicIH.java.076340fb58b51758a1bd428ddde6ce8e
cl40: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl40.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/LocalMusicPresenter.java.8d256cede6e09896f3a8ea584658421b
cl41: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl41.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/Lyric.java.74c09d5dc4a2d022fa4c9557db40bdca
cl42: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl42.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/LyricResult.java.bdf4ba8346d7f112a071a8b8ddace5b4
cl43: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl43.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/LyricView.java.aab1359786a514893248f8c9c146a410
cl44: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl44.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/MainActivity.java.70699a6627b3c2ea37922e558e977d39
cl45: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl45.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/MainDrawerAdapter.java.f93518791cc98dc5dce632dc95c75fde
cl46: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl46.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/MainUIFragmentIndex.java.0e56b8c25fb276c11aa615c2239983bc
cl47: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl47.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/Md5Utils.java.ef1b42436dbaf306e1be69a0a5b084b6
cl48: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl48.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/MediaPlayerContract.java.616935d123fa1f76b44973ce90546c2a
cl49: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl49.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/MediaPlayerThumb.java.af485192c53702a3171b0897e67f990d
cl50: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl50.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/MediaPlayPresenter.java.35be813eaca56a0c91b162060eabf6c6
cl51: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl51.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/MediaSeekBar.java.979e86890174b96c2c912280a3266f74
cl52: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl52.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/MusicControlPanel.java.26b19465c5b0f35f0b2ee193125c9c69
cl53: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl53.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/MusicDbOperator.java.fd93d9e8f913de22475d14226674ed24
cl54: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl54.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/MusicDownIH.java.1e9afbd770e3416d1fa8855fb4f7041b
cl55: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl55.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/MusicDownLoadListActivity.java.4b2c57edfdfab0327446e45422a8db11
cl56: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl56.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/MusicInstruction.java.a77ddf5b0275b4eec8cd9cd345741baa
cl57: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl57.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/MusicPageAdapter.java.55a898ea238789a566191cf69c96805e
cl58: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl58.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/MusicPageBaseFragment.java.37b209f1d0f9e3b2fd837b21b4b323d7
cl59: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl59.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/MusicPageConstantIH.java.ced9087c786101379f8578c91d26627a
cl60: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl60.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/MusicPageConstantItem.java.71cd5140c2aff5363f38ced1d184a333
cl61: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl61.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/MusicPageFragment.java.8dff3919b07f9809c8b98591a9bc8142
cl62: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl62.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/MusicPagePlayListIH.java.fb2b54fcce231e8d1b07e259817179c7
cl63: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl63.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/MusicPageTitleIH.java.3cfc9109d5324da671ce8a313438ebfa
cl64: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl64.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/MusicPlayControlView.java.7fabc1721abbf53eb80bff148874d663
cl65: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl65.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/MusicPlayerService.java.f08e39a237f2de8278287c0ace889937
cl66: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl66.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/MusicPlayQueueControlPresenter.java.2057a8e4b93fec9e0dc9125115621aba
cl67: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl67.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/MusicSearchResult.java.5296e88538f1d90babcaa91fe282f7cf
cl68: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl68.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/MusicSearchResultAdapter.java.db0f3e73034f700c0f09addec094c384
cl69: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl69.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/MusicServiceContract.java.ccb62ee064c2ebed67ac8960cd4b132f
cl70: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl70.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/MusicServices.java.450aa341282137a70c36601c3f0ac40e
cl71: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl71.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/MyMusicCollectActivity.java.375bd81f09257e2567d6dbf2d859ba84
cl72: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl72.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/NestScrollView.java.1d736174be71dfcd82973099613f45ca
cl73: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl73.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/OnLastItemVisibleListener.java.f4e3d5d7d4bd4ee9d5a27de26d5f75d5
cl74: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl74.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/PlayerPageFragment.java.46603a207d44ea0a8f08bf4242eb0648
cl75: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl75.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/PlayList.java.fd971cf7fdb0f9fa700785b42905169d
cl76: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl76.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/PlayListActivity.java.795aa9041610792be3a8f56da569c8ea
cl77: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl77.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/PlayListDetail.java.08f0427d01f2c8538e112749e5dfc7e4
cl78: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl78.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/PlayListSong.java.a11e0a4fe11d17f92731fab29871a9ca
cl79: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl79.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/PlayMusicActivity.java.8eda9e3a9b46426fa10b106f36179749
cl80: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl80.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/PlayMusicPresenter.java.780f5f465b2c2cad562aeaa806c07873
cl81: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl81.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/PlayOperatorView.java.9b266d86f9ace30b6fceb48f2416d65e
cl82: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl82.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/R.java.0a9a7965dc8cf14ee909c31ab551734e
cl83: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl83.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/R.java.0d4957cd90db13b449c551e3ba08ca3c
cl84: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl84.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/R.java.12530ae6387a8aac9efbdb8af4d3b8c4
cl85: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl85.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/R.java.2e4c27d9437c48d3e895d164d19dcc24
cl86: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl86.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/R.java.3e4aacc57513d7c1624cd8647f17f46d
cl87: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl87.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/R.java.48b7859c30db1941cf1249ede50a66e8
cl88: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl88.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/R.java.843b4c2aa62763908339c2b13acbbb0c
cl89: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl89.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/R.java.9bc0817e01e6c9045494205f3539dc78
cl90: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl90.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/R.java.ab15cd3b1cc05a6ce0a3ade0a3a34e08
cl91: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl91.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/R.java.ae63b8e54ad219c69d30d6953d022758
cl92: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl92.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/R.java.bcd36211b0c98bc85b4580dd0e3c33ec
cl93: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl93.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/R.java.bcdb1987441e1a994c92a27fdfa6c94e
cl94: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl94.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/R.java.d6bbda2dfc8695130ddf5ddf4dce2b25
cl95: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl95.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/R.java.dad6fb845d8d1299e27d116a3556081a
cl96: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl96.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/R.java.dd74ce5794c320ac9a8280144c3e6734
cl97: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl97.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/R.java.f93c4aded6167ab93392da803fd76e65
cl98: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl98.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/RVUtils.java.4ce48ea835040f9600e4d733fb8ac92a
cl99: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl99.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/SAppApplication.java.490af80efe2ba48cfa6c917c3a9e7c03
cl100: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl100.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/SchedulerTransform.java.ed031d66f78a06d58bb4377c53e8f138
cl101: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl101.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/SearchBar.java.4b59d685f4a883017f580c86a6722919
cl102: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl102.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/SearchMusicActivity.java.53bc8e9eb8e6ec81f4dad9adb6db74e7
cl103: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl103.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/SearchMusicResultIH.java.6e2a8d9f649daefe17edbfb16d21f441
cl104: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl104.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/ServiceReceiverPresenter.java.406f8d0817e29983f5ff7277da4925fd
cl105: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl105.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/SimpleItemHandler.java.b439300938a0f145fe231645b3ac272d
cl106: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl106.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/SimpleSong.java.fd16e9cbbcd5f5496401b7e33e4c2198
cl107: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl107.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/SimpleTitle.java.11521d6a22bf4c1dd5a7a3322a687b5c
cl108: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl108.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/Singer.java.46096e00b83814d3ef41ac7d55593867
cl109: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl109.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/Song.java.181a7f8121e4513a544ed68983cc7127
cl110: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl110.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/SplashActivity.java.88aaea1c15d72e8b0600d405a18d8ae6
cl111: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl111.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/SPUtils.java.1f881e0bfb6386272d25d20a00d765e2
cl112: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl112.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/StatusBarUtil.java.18520c9186f4368000b723e039cf1354
cl113: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl113.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/StatusBarView.java.2724659962e1bf09b027953799cf22a7
cl114: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl114.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/SToolBar.java.0f3edde018f5f454bacab990218191ed
cl115: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl115.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/SwipeBackActivity.java.8eb33d5eee35bbe659f6d33b4a7a5249
cl116: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl116.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/SwipeBackActivityBase.java.0615d74388b9658b4a2f91bb417d8639
cl117: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl117.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/SwipeBackActivityHelper.java.f0c76d1091429f682c8fe4e0292eb076
cl118: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl118.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/SwipeBackLayout.java.bf20ca4aa37a8c8dbd5e4e71089c57d1
cl119: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl119.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/SystemOperationUtils.java.039b8577ec8a2d1590665d085c77bd76
cl120: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl120.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/TimeUtils.java.5849acd1de52b6577393108f463499be
cl121: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl121.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/ToastUtils.java.fec38282d25a249fdcaa1efc86927209
cl122: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl122.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/TransitionHelper.java.72c058bff889814c397a46e478659279
cl123: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl123.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/UIUtils.java.60dab27abde89990aa7b868c5795db48
cl124: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl124.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/Utils.java.114a1fce12931f158504a5185fa335d5
cl125: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl125.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/ViewDragHelper.java.c1ebe46d1ea139c0afbc95fa7a66669b
cl126: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl126.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/ViewHolder.java.168c331a64b0e760e49596a1fae7cf52
cl127: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl127.cluster'
	@touch $@

#/Users/susion/Documents/Code/myproject/Boring/infer-out/captured/WaterWaveRotateImageView.java.3e24c995806f933d8d14dffc31e3965c
cl128: 
	$(INFERANALYZE) --cluster '/Users/susion/Documents/Code/myproject/Boring/infer-out/multicore/xcl128.cluster'
	@touch $@


clean:
	rm -f $(CLUSTERS)
