package com.susion.boring.music.service;

/**
 * Created by susion on 17/2/13.
 */
public class MusicInstruction {

    //service
    public static final String SERVICE_RECEIVER_PLAY_MUSIC = "SERVICE_RECEIVER_PLAY_MUSIC";
    public static final String SERVICE_RECEIVER_PAUSE_MUSIC = "SERVICE_RECEIVER_PAUSE_MUSIC";
    public static final String SERVICE_RECEIVER_SEEK_TO = "SERVICE_RECEIVER_SEEK_TO";
    public static final String SERVICE_PARAM_SEEK_TO_POS = "SERVICE_PARAM_SEEK_TO_POS";
    public static final String SERVICE_SAVE_LAST_PLAY_MUSIC = "SERVICE_SAVE_LAST_PLAY_MUSIC";

    //client
    public static final String CLIENT_ACTION_MUSIC_INFO = "CLIENT_ACTION_MUSIC_INFO";
    public static final String CLIENT_RECEIVER_PLAYER_PREPARED = "CLIENT_RECEIVER_PLAYER_PREPARED";
    public static final String CLIENT_RECEIVER_UPDATE_BUFFERED_PROGRESS = "CLIENT_RECEIVER_UPDATA_BUFFERED_PROGRESS";
    public static final String CLIENT_RECEIVER_UPDATE_PLAY_PROGRESS = "CLIENT_RECEIVER_UPDATE_PLAY_PROGRESS";
    public static final String CLIENT_PARAM_BUFFERED_PROGRESS = "CLIENT_PARAM_BUFFERED_PROGRESS";
    public static final String CLIENT_PARAM_PLAY_PROGRESS_CUR_POS = "CLIENT_PARAM_PLAY_PROGRESS_CUR_POS";
    public static final String CLIENT_PARAM_PLAY_PROGRESS_DURATION = "CLIENT_PARAM_PLAY_PROGRESS__DURATION";
    public static final String CLIENT_PARAM_PREPARED_TOTAL_DURATION = "CLIENT_PARAM_PREPARED_TOTAL_DURATION";


}
