package com.susion.boring.music.service;

import android.content.Context;
import android.content.Intent;

import com.susion.boring.music.activity.PlayMusicActivity;
import com.susion.boring.music.model.Song;

/**
 * Created by susion on 17/2/13.
 */
public class MusicInstruction {

    //service
    public static final String SERVICE_RECEIVER_QUERY_CURRENT_STATE = "SERVICE_RECEIVER_QUERY_CURRENT_STATE";
    public static final String SERVICE_RECEIVER_PLAY_MUSIC = "SERVICE_RECEIVER_PLAY_MUSIC";
    public static final String SERVICE_RECEIVER_PAUSE_MUSIC = "SERVICE_RECEIVER_PAUSE_MUSIC";
    public static final String SERVICE_RECEIVER_SEEK_TO = "SERVICE_RECEIVER_SEEK_TO";
    public static final String SERVICE_PARAM_SEEK_TO_POS = "SERVICE_PARAM_SEEK_TO_POS";
    public static final String SERVICE_SAVE_LAST_PLAY_MUSIC = "SERVICE_SAVE_LAST_PLAY_MUSIC";
    public static final String SERVICE_CURRENT_PLAY_MUSIC = "SERVICE_CURRENT_PLAY_MUSIC";
    public static final String SERVICE_LOAD_MUSIC_INFO = "LOAD_MUSIC_INFO";
    public static final String SERVICE_PARAM_PLAY_SONG = "SERVICE_PARAM_PLAY_SONG";
    public static final String SERVICE_PARAM_IS_PLAY = "SERVICE_PARAM_IS_PLAY";
    public static final String SERVER_RECEIVER_CHANGE_MUSIC = "SERVER_RECEIVER_CHANGE_MUSIC";
    public static final String SERVICE_PARAM_CHANGE_MUSIC = "SERVICE_PARAM_CHANGE_MUSIC";
    public static final String SERVICE_RECEIVER_QUERY_IS_PLAYING = "SERVICE_RECEIVER_QUERY_IS_PLAYING";
    public static final String SERVICE_RECEIVER_GET_PLAY_PROGRESS = "SERVICE_RECEIVER_GET_PLAY_PROGRESS";
    public static final String SERVICE_PARAM_PLAY_SONG_AUTO_PLAY = "SERVICE_PARAM_PLAY_SONG_AUTO_PLAY";
    public static final String SERVER_RECEIVER_UPDATE_PLAY_MUSIC_INFO = "SERVER_RECEIVER_UPDATE_PLAY_MUSIC_INFO";
    public static final String SERVICE_PARAM_UPDATE_SONG = "SERVICE_PARAM_UPDATE_SONG";
    public static final String SERVER_RECEIVER_PLAY_NEXT = "SERVER_RECEIVER_PLAY_NEXT";
    public static final String SERVER_RECEIVER_PLAY_PRE = "SERVER_RECEIVER_PLAY_PRE";
    public static final String SERVER_RECEIVER_SONG_TO_NEXT_PLAY = "SERVER_RECEIVER_SONG_TO_NEXT_PLAY";
    public static final String SERVER_RECEIVER_PLAY_MODE_RANDOM = "SERVER_RECEIVER_PLAY_MODE_RANDOM";
    public static final String SERVER_RECEIVER_PLAY_MODE_CIRCLE = "SERVER_RECEIVER_PLAY_MODE_CIRCLE";
    public static final String SERVICE_PARAM_SONG_TO_NEXT_PLAY = "SERVICE_PARAM_SONG_TO_NEXT_PLAY";
    public static final String SERVER_RECEIVER_SONG_QUERY_CUR_MODE = "SERVER_RECEIVER_SONG_QUERY_CUR_MODE";
    public static final String SERVER_RECEIVER_CIRCLE_PLAY_PLAY_LIST = "SERVER_RECEIVER_CIRCLE_PLAY_PLAY_LIST";
    public static final String SERVICE_PARAM_PLAY_LIST = "SERVICE_PARAM_PLAY_LIST";
    public static final String SERVER_RECEIVER_GET_PLAY_QUEUE = "SERVER_RECEIVER_GET_PLAY_QUEUE";
    public static final String SERVER_RECEIVER_RANDOM_PLAY_PLAY_LIST = "SERVER_RECEIVER_RANDOM_PLAY_PLAY_LIST";
    public static final String SERVER_RECEIVER_REMOVE_SONG_FROM_QUEUE = "SERVER_RECEIVER_REMOVE_SONG_FROM_QUEUE";
    public static final String SERVICE_PARAM_REMOVE_SONG = "SERVICE_PARAM_REMOVE_SONG";
    public static final String SERVER_RECEIVER_PLAY_MODE_QUEUE = "SERVER_RECEIVER_PLAY_MODE_QUEUE" ;



    //client
    public static final String CLIENT_ACTION_MUSIC_INFO = "CLIENT_ACTION_MUSIC_INFO";
    public static final String CLIENT_RECEIVER_CURRENT_SERVER_STATE = "CLIENT_RECEIVER_CURRENT_SERVER_STATE";
    public static final String CLIENT_RECEIVER_PLAYER_PREPARED = "CLIENT_RECEIVER_PLAYER_PREPARED";
    public static final String CLIENT_RECEIVER_UPDATE_BUFFERED_PROGRESS = "CLIENT_RECEIVER_UPDATA_BUFFERED_PROGRESS";
    public static final String CLIENT_RECEIVER_UPDATE_PLAY_PROGRESS = "CLIENT_RECEIVER_UPDATE_PLAY_PROGRESS";
    public static final String CLIENT_PARAM_BUFFERED_PROGRESS = "CLIENT_PARAM_BUFFERED_PROGRESS";
    public static final String CLIENT_PARAM_PLAY_PROGRESS_CUR_POS = "CLIENT_PARAM_PLAY_PROGRESS_CUR_POS";
    public static final String CLIENT_PARAM_PLAY_PROGRESS_DURATION = "CLIENT_PARAM_PLAY_PROGRESS__DURATION";
    public static final String CLIENT_PARAM_PREPARED_TOTAL_DURATION = "CLIENT_PARAM_PREPARED_TOTAL_DURATION";
    public static final String CLIENT_RECEIVER_CURRENT_PLAY_MUSIC = "CLIENT_RECEIVER_CURRENT_PLAY_MUSIC";
    public static final String CLIENT_PARAM_CURRENT_PLAY_MUSIC = "CLIENT_PARAM_CURRENT_PLAY_MUSIC";
    public static final String CLIENT_PARAM_SERVER_STATE = "CLIENT_PARAM_SERVER_STATE";
    public static final String CLIENT_RECEIVER_SET_DURATION = "CLIENT_RECEIVER_SET_DURATION";
    public static final String CLIENT_PARAM_MEDIA_DURATION = "CLIENT_PARAM_MEDIA_DURATION";
    public static final String CLIENT_RECEIVER_CURRENT_IS_PALING = "CLIENT_RECEIVER_CURRENT_IS_PALING";
    public static final String CLIENT_PARAM_IS_PLAYING = "CLIENT_PARAM_IS_PLAYING";
    public static final String CLIENT_RECEIVER_CURRENT_PLAY_PROGRESS = "CLIENT_RECEIVER_CURRENT_PLAY_PROGRESS";
    public static final String CLIENT_PARAM_CURRENT_PLAY_PROGRESS = "CLIENT_PARAM_CURRENT_PLAY_PROGRESS";
    public static final String CLIENT_PARAM_NEED_LOAD_MUSIC = "CLIENT_PARAM_NEED_LOAD_MUSIC";
    public static final String CLIENT_RECEIVER_REFRESH_MUSIC = "CLIENT_RECEIVER_REFRESH_MUSIC";
    public static final String CLIENT_PARAM_REFRESH_SONG = "CLIENT_PARAM_REFRESH_SONG";
    public static final String CLIENT_RECEIVER_REFRESH_MODE = "CLIENT_RECEIVER_REFRESH_MODE";
    public static final String CLIENT_PARAM_PLAY_MODE = "CLIENT_PARAM_PLAY_MODE";
    public static final String CLIENT_RECEIVER_PLAY_QUEUE = "CLIENT_RECEIVER_PLAY_QUEUE";
    public static final String CLIENT_PARAM_PLAY_QUEUE = "CLIENT_PARAM_PLAY_QUEUE";


}
